name: Convert Excel to JSON

on:
  push:
    paths:
      - "My Cellar.csv"
      - "watch_and_convert.py"

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          # Pin Python version compatible with pandas==1.5.3
          python-version: '3.10'

      - name: Install dependencies
        run: |
          # Pin compatible versions of Pandas and NumPy
          pip install pandas==1.5.3 numpy==1.24.3 watchdog==2.3.0

      - name: Convert CSV to JSON
        run: |
          python convert_once.py "My Cellar.csv" wine-data.json

      - name: Commit updated JSON
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Auto-convert Excel to JSON [skip ci]'
          add: 'wine-data.json'